'use client';
import { use, useEffect, useState } from 'react';
import { Clock3, MapPin, Package, Search, Truck } from 'lucide-react';
import { Locale } from '@/lib/i18n';
import { apiFetch } from '@/lib/api-client';

type Parcel={id:string;parcelCode:string;trackingCodeChina:string;status:string;chargeableWeight:number;currentWarehouse?:{name:string}|null;updatedAt:string};
type Transport={id:string;requestCode:string;goodsDescription:string;categoryName:string;chargeableWeight:number;pickupProvince:string;province:string;status:string;updatedAt:string};
const meta:Record<string,{label:string;step:number;color:string}>={RECEIVED_CHINA:{label:'Đã nhận tại kho Trung Quốc',step:1,color:'text-indigo-700 bg-indigo-50'},IN_TRANSIT:{label:'Đang vận chuyển về Việt Nam',step:2,color:'text-sky-700 bg-sky-50'},RECEIVED_VIETNAM:{label:'Đã về kho Việt Nam',step:3,color:'text-emerald-700 bg-emerald-50'}};

export default function ShipmentsPage({params}:{params:Promise<{locale:Locale}>}){
  use(params);const[parcels,setParcels]=useState<Parcel[]>([]);const[requests,setRequests]=useState<Transport[]>([]);const[search,setSearch]=useState('');const[loading,setLoading]=useState(true);
  useEffect(()=>{Promise.all([apiFetch('/packages'),apiFetch('/packages/transport-requests/mine')]).then(async([a,b])=>{const[aj,bj]=await Promise.all([a.json(),b.json()]);if(!a.ok)throw new Error(aj.message);if(!b.ok)throw new Error(bj.message);setParcels((aj.data||[]).filter((x:Parcel)=>meta[x.status]));setRequests((bj.data||[]).filter((x:Transport)=>x.status==='IN_TRANSIT'))}).catch(error=>console.error('Không thể tải dữ liệu đang vận chuyển:',error)).finally(()=>setLoading(false))},[]);
  const q=search.toLowerCase();const shownParcels=parcels.filter(x=>`${x.parcelCode} ${x.trackingCodeChina}`.toLowerCase().includes(q));const shownRequests=requests.filter(x=>`${x.requestCode} ${x.goodsDescription} ${x.categoryName}`.toLowerCase().includes(q));
  return <div className="space-y-4 text-slate-800">
    <div className="rounded-2xl border border-slate-200 bg-white p-5"><h1 className="flex items-center gap-2 font-bold"><Truck className="h-5 w-5 text-[#0c3ed0]"/>Đang vận chuyển ({parcels.length+requests.length})</h1><p className="mt-1 text-xs text-slate-500">Theo dõi yêu cầu và kiện hàng đang di chuyển từ Trung Quốc về Việt Nam.</p></div>
    <div className="relative rounded-2xl border border-slate-200 bg-white p-4"><Search className="absolute left-7 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm mã yêu cầu, mã kiện hoặc mã vận đơn" className="w-full rounded-xl border bg-slate-50 py-2.5 pl-10 pr-3 text-sm"/></div>
    {loading?<div className="rounded-2xl bg-white p-8 text-center text-sm">Đang tải dữ liệu...</div>:shownParcels.length+shownRequests.length===0?<div className="rounded-2xl border bg-white p-10 text-center"><Package className="mx-auto mb-2 h-9 w-9 text-slate-300"/><p className="text-sm font-semibold">Không có hàng đang vận chuyển</p></div>:<div className="space-y-3">
      {shownRequests.map(x=><div key={`request-${x.id}`} className="rounded-2xl border border-sky-200 bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><b className="font-mono text-sm text-blue-700">{x.requestCode}</b><p className="mt-1 text-xs text-slate-500">{x.categoryName} • {x.goodsDescription}</p></div><span className="h-fit rounded-full bg-sky-50 px-3 py-1 text-[11px] font-bold text-sky-700">Đang vận chuyển</span></div><div className="mt-4 grid gap-3 border-t pt-3 text-xs text-slate-600 sm:grid-cols-3"><span className="flex gap-1"><Package className="h-4 w-4"/>{Number(x.chargeableWeight||0).toFixed(2)} kg</span><span className="flex gap-1"><MapPin className="h-4 w-4"/>{x.pickupProvince} → {x.province}</span><span className="flex gap-1"><Clock3 className="h-4 w-4"/>Cập nhật {new Date(x.updatedAt).toLocaleString('vi-VN')}</span></div></div>)}
      {shownParcels.map(x=>{const state=meta[x.status];return <div key={x.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><b className="font-mono text-sm text-blue-700">{x.parcelCode}</b><p className="mt-1 text-xs text-slate-500">Mã TQ: {x.trackingCodeChina}</p></div><span className={`h-fit rounded-full px-3 py-1 text-[11px] font-bold ${state.color}`}>{state.label}</span></div><div className="my-5 flex items-center">{['Kho Trung Quốc','Đang di chuyển','Kho Việt Nam'].map((label,index)=><div key={label} className="flex flex-1 items-center last:flex-none"><div className="flex flex-col items-center"><div className={`grid h-7 w-7 place-items-center rounded-full text-xs font-bold ${index<state.step?'bg-[#0c3ed0] text-white':'bg-slate-200 text-slate-500'}`}>{index+1}</div><span className="mt-1 whitespace-nowrap text-[10px] font-semibold">{label}</span></div>{index<2&&<div className={`mx-2 h-1 flex-1 rounded ${index<state.step-1?'bg-[#0c3ed0]':'bg-slate-200'}`}/>}</div>)}</div><div className="flex flex-wrap gap-5 border-t pt-3 text-xs text-slate-600"><span className="flex gap-1"><Package className="h-4 w-4"/>{Number(x.chargeableWeight).toFixed(2)} kg</span><span className="flex gap-1"><MapPin className="h-4 w-4"/>{x.currentWarehouse?.name||'Đang cập nhật vị trí'}</span><span className="flex gap-1"><Clock3 className="h-4 w-4"/>Cập nhật {new Date(x.updatedAt).toLocaleString('vi-VN')}</span></div></div>})}
    </div>}
  </div>;
}
