'use client';
import { useCallback, useEffect, useState } from 'react';
import { CalendarClock, RefreshCw, Save } from 'lucide-react';
import { apiFetch } from '@/lib/api-client';

export default function AdminAffiliatePayrollPage() {
  const [month,setMonth]=useState(new Date().toISOString().slice(0,7)); const [data,setData]=useState<any>(null); const [salary,setSalary]=useState(2000000); const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);try{const r=await apiFetch(`/affiliates/attendance/admin?month=${month}`);const j=await r.json();if(!r.ok)throw new Error(j.message);setData(j.data);setSalary(j.data.policy.baseSalaryVnd);}catch(e:any){alert(e.message)}finally{setLoading(false)}},[month]);
  useEffect(()=>{void load()},[load]);
  const save=async()=>{try{const r=await apiFetch('/affiliates/attendance/policy',{method:'PUT',body:JSON.stringify({baseSalaryVnd:salary})});const j=await r.json();if(!r.ok)throw new Error(j.message);await load();alert('Đã lưu lương cơ bản toàn hệ thống');}catch(e:any){alert(e.message)}};
  const review=async(id:string,status:string)=>{try{const r=await apiFetch(`/affiliates/leave-requests/${id}`,{method:'PATCH',body:JSON.stringify({status})});const j=await r.json();if(!r.ok)throw new Error(j.message);await load();}catch(e:any){alert(e.message)}};
  return <div className="space-y-6 text-slate-900"><div className="rounded-3xl bg-slate-900 p-6 text-white"><div className="flex items-center gap-2 text-xs font-bold text-amber-400"><CalendarClock className="h-4 w-4"/>QUẢN TRỊ NHÂN SỰ ĐỐI TÁC</div><h1 className="mt-1 text-2xl font-bold">Chấm Công &amp; Bảng Lương</h1></div>
  <div className="flex flex-wrap items-end gap-3 rounded-2xl border bg-white p-4"><label className="text-xs font-bold">Tháng<input type="month" value={month} onChange={e=>setMonth(e.target.value)} className="mt-1 block rounded-xl border px-3 py-2"/></label><label className="text-xs font-bold">Lương cơ bản toàn hệ thống<input type="number" min="0" value={salary} onChange={e=>setSalary(Number(e.target.value))} className="mt-1 block rounded-xl border px-3 py-2 font-mono"/></label><button onClick={()=>void save()} className="flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2 text-xs font-bold text-white"><Save className="h-4 w-4"/>Lưu chính sách</button><button onClick={()=>void load()} className="flex items-center gap-2 rounded-xl bg-slate-100 px-4 py-2 text-xs font-bold"><RefreshCw className="h-4 w-4"/>Làm mới</button></div>
  <div className="rounded-3xl border bg-white p-5"><h2 className="mb-4 font-bold">Bảng công và lương tháng</h2>{loading?'Đang tải...':<div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-xs"><thead><tr className="border-b text-[10px] uppercase text-slate-500"><th className="pb-3">Đối tác</th><th className="pb-3">Trạng thái</th><th className="pb-3 text-right">Ngày công</th><th className="pb-3 text-right">Phép có lương</th><th className="pb-3 text-right">Chuẩn tháng</th><th className="pb-3 text-right">Lương tạm tính</th></tr></thead><tbody className="divide-y">{data?.payroll?.map((p:any)=><tr key={p.id}><td className="py-3"><b>{p.fullName}</b><div className="text-[10px] text-slate-400">{p.customerCode} • {p.email}</div></td><td>{p.status}</td><td className="text-right font-mono">{p.attendedDays}</td><td className="text-right font-mono">{p.paidLeaveDays}</td><td className="text-right font-mono">{p.standardDays}</td><td className="text-right font-mono font-bold text-emerald-600">{p.salaryVnd.toLocaleString('vi-VN')} ₫</td></tr>)}</tbody></table></div>}</div>
  <div className="rounded-3xl border bg-white p-5"><h2 className="mb-4 font-bold">Yêu cầu nghỉ phép</h2><div className="divide-y">{data?.leaves?.map((l:any)=><div key={l.id} className="flex flex-col gap-2 py-3 text-xs sm:flex-row sm:items-center sm:justify-between"><div><b>{l.user.fullName}</b> • {l.leaveDate} • {l.leaveType==='PAID'?'Có lương':'Không lương'}<div className="text-slate-500">{l.reason}</div></div><div>{l.status==='PENDING'?<span className="flex gap-2"><button onClick={()=>void review(l.id,'APPROVED')} className="rounded-lg bg-emerald-600 px-3 py-1.5 font-bold text-white">Duyệt</button><button onClick={()=>void review(l.id,'REJECTED')} className="rounded-lg bg-rose-600 px-3 py-1.5 font-bold text-white">Từ chối</button></span>:<b>{l.status}</b>}</div></div>)}</div></div>
  </div>;
}
