'use client';
import { useCallback, useEffect, useState } from 'react';
import { CalendarDays, Wallet } from 'lucide-react';
import { apiFetch } from '@/lib/api-client';

export default function AffiliatePayrollPage(){
  const [month,setMonth]=useState(new Date().toISOString().slice(0,7));const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(true);const[leaveDate,setLeaveDate]=useState('');const[reason,setReason]=useState('');
  const load=useCallback(async()=>{setLoading(true);try{const r=await apiFetch(`/affiliates/attendance/me?month=${month}`);const j=await r.json();if(!r.ok)throw new Error(j.message);setData(j.data)}catch(e:any){alert(e.message)}finally{setLoading(false)}},[month]);useEffect(()=>{void load()},[load]);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();try{const r=await apiFetch('/affiliates/leave-requests',{method:'POST',body:JSON.stringify({leaveDate,reason})});const j=await r.json();if(!r.ok)throw new Error(j.message);setLeaveDate('');setReason('');await load()}catch(e:any){alert(e.message)}};const s=data?.summary||{};
  return <div className="space-y-6 text-slate-900"><div className="rounded-3xl bg-slate-900 p-6 text-white"><div className="text-xs font-bold text-amber-400">THU NHẬP ĐỐI TÁC</div><h1 className="mt-1 text-2xl font-bold">Lương &amp; Lịch Off</h1><p className="mt-1 text-xs text-slate-400">Chủ nhật nghỉ cố định • 1 ngày phép hưởng lương mỗi tháng</p></div><div className="flex justify-end"><input type="month" value={month} onChange={e=>setMonth(e.target.value)} className="rounded-xl border px-3 py-2 text-sm"/></div>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Lương cơ bản',data?.policy?.baseSalaryVnd||0,'₫'],['Ngày công',s.attendedDays||0,`/${s.standardDays||0}`],['Phép có lương',s.paidLeaveDays||0,' ngày'],['Lương tạm tính',s.estimatedSalaryVnd||0,'₫']].map(([l,v,x])=><div key={String(l)} className="rounded-2xl border bg-white p-4"><div className="text-[10px] font-bold uppercase text-slate-400">{l}</div><div className="mt-1 font-mono text-xl font-bold">{Number(v).toLocaleString('vi-VN')} {x}</div></div>)}</div>
  <div className="grid gap-5 lg:grid-cols-2"><div className="rounded-3xl border bg-white p-5"><h2 className="mb-4 flex items-center gap-2 font-bold"><CalendarDays className="h-4 w-4"/>Đăng ký lịch off</h2><form onSubmit={submit} className="space-y-3"><input required type="date" value={leaveDate} onChange={e=>setLeaveDate(e.target.value)} className="w-full rounded-xl border px-3 py-2 text-sm"/><textarea required value={reason} onChange={e=>setReason(e.target.value)} placeholder="Lý do nghỉ phép" className="w-full rounded-xl border px-3 py-2 text-sm"/><button className="rounded-xl bg-amber-500 px-4 py-2 text-xs font-bold text-white">Gửi yêu cầu off</button></form></div><div className="rounded-3xl border bg-white p-5"><h2 className="mb-4 flex items-center gap-2 font-bold"><Wallet className="h-4 w-4"/>Lịch nghỉ đã đăng ký</h2>{loading?'Đang tải...':<div className="divide-y">{data?.leaves?.map((l:any)=><div key={l.id} className="flex justify-between gap-3 py-3 text-xs"><span><b>{l.leaveDate}</b> • {l.reason}<small className="ml-1 text-slate-400">({l.leaveType==='PAID'?'Có lương':'Không lương'})</small></span><b className={l.status==='APPROVED'?'text-emerald-600':l.status==='REJECTED'?'text-rose-600':'text-amber-600'}>{l.status==='APPROVED'?'Đã duyệt':l.status==='REJECTED'?'Từ chối':'Chờ duyệt'}</b></div>)}{!data?.leaves?.length&&<p className="text-sm text-slate-500">Chưa có lịch off.</p>}</div>}</div></div></div>;
}
